[package]
name = "validator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base ={ path = "../base"}
rocket = { version = "0.5.0", features = [ "json" ]}
serde = "1.0.195"
serde_json = "1.0.111"
